# This file is part of tilda_wrapper_api.
# https://github.com/ozeranskiy/tilda_wrapper_api

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2019, Sergey Ozeranskiy <sergey.ozeranskiy@gmail.com>

dist: xenial

language: python

python:
    - '3.7'

install:
    # install python requirements
    - make init

script:
    # run tests
    - make test

after_success:
    - coveralls